const mailingListSettingsFile = {
  label: 'Mailing List Settings',
  name: 'mailingListSettings',
  file: 'settings/mailing-list/mailing-list-settings.yml',
  fields: [
    {
      label: 'Mailing List Form ID',
      name: 'mailingListFormId',
      widget: 'string',
      hint: 'The ID of the form to use for the mailing list. This is defined in Form Settings.',
    },
    {
      label: 'Sidebar Mailing List Widget',
      name: 'sidebarWidget',
      widget: 'object',
      hint: 'Settings for the sidebar widget.',
      fields: [
        {
          label: 'Enable Mailing List Sidebar Widget',
          name: 'enabled',
          widget: 'boolean',
          hint: 'Turns the sidebar mailing list widget on/off.',
        },
        {
          label: 'Header Image',
          name: 'headerImage',
          widget: 'image',
          hint: 'The header image shown at the top of the sidebar widget.',
        },
        {
          label: 'Title Text',
          name: 'titleText',
          widget: 'string',
          hint: 'The title text. This catchy headline should entice the reader into signing up!',
        },
        {
          label: 'Body Text',
          name: 'bodyText',
          widget: 'text',
          hint: 'The body text. Explain the benefits of signing up here. Make it irresistible. Supports HTML.',
        },
        {
          label: 'Button Text',
          name: 'buttonText',
          widget: 'string',
          hint: 'The text shown on the submit button.',
        },
        {
          label: 'Privacy Text',
          name: 'privacyText',
          widget: 'string',
          hint: 'The text shown under the email field that assures the user their privacy is important to you.',
        },
        {
          label: 'Error Submitting Text',
          name: 'errorSubmittingText',
          widget: 'string',
          hint: 'The text shown when there is an error submitting the form.',
        },
        {
          label: 'Success Image',
          name: 'successImage',
          widget: 'image',
          hint: 'The success image, shown in place of the header image when submitting is successful.',
        },
        {
          label: 'Success Title Text',
          name: 'successTitleText',
          widget: 'string',
          hint: 'The title text shown when finished submitting.',
        },
        {
          label: 'Success Body Text',
          name: 'successBodyText',
          widget: 'text',
          hint: 'The message shown when finished submitting. Supports HTML.',
        },
      ],
    },
    {
      label: 'Footer Mailing List Section',
      name: 'footerMailingListSection',
      widget: 'object',
      hint: 'Settings for the footer mailing list section.',
      fields: [
        {
          label: 'Enable Mailing List Footer Section',
          name: 'enabled',
          widget: 'boolean',
          hint: 'Turns the footer mailing list section on/off.',
        },
        {
          label: 'Background Image',
          name: 'backgroundImage',
          widget: 'image',
          hint: 'The image shown in the background of the section.',
        },
        {
          label: 'Background Image Brightness',
          name: 'backgroundImageBrightness',
          widget: 'number',
          valueType: 'int',
          min: 0,
          max: 100,
          step: 1,
          hint: 'How bright the image appears on a scale from 0-100, 0 being darkest.',
        },
        {
          label: 'Title Text',
          name: 'titleText',
          widget: 'string',
          hint: 'The title text. This catchy headline should entice the reader into signing up!',
        },
        {
          label: 'Body Text',
          name: 'bodyText',
          widget: 'text',
          hint: 'The body text. Explain the benefits of signing up here. Make it irresistible. Supports HTML.',
        },
        {
          label: 'Button Text',
          name: 'buttonText',
          widget: 'string',
          hint: 'The text shown on the submit button.',
        },
        {
          label: 'Privacy Text',
          name: 'privacyText',
          widget: 'string',
          hint: 'The text shown under the email field that assures the user their privacy is important to you.',
        },
        {
          label: 'Error Submitting Text',
          name: 'errorSubmittingText',
          widget: 'string',
          hint: 'The text shown when there is an error submitting the form.',
        },
        {
          label: 'Success Image',
          name: 'successImage',
          widget: 'image',
          hint: 'The success image, shown in place of the background image when submitting is successful.',
        },
        {
          label: 'Success Title Text',
          name: 'successTitleText',
          widget: 'string',
          hint: 'The title text shown when finished submitting.',
        },
        {
          label: 'Success Body Text',
          name: 'successBodyText',
          widget: 'text',
          hint: 'The message shown when finished submitting. Supports HTML.',
        },
      ],
    },
  ],
};

export default mailingListSettingsFile;
